### PR TITLE
feat: run remote commands in parallel

### PR DESCRIPTION
**Pull request by Rauno56**
... and fix some bugs. I'm thinking of what's a good worker count. I'll test that...

### CODE REVIEW

**Comment by Rauno56** [comment]
I think it's done for now.

**Comment by Rauno56** [comment]
I think it's done now, @kanolato.

**Comment by kanolato** [comment]
works really well! 
I only have some comments about making the tool require: SECRETS_ORG, SECRETS_REPO_HOST. One could give the key and keyring from flags or environment variables and there would be no need for SECRETS_ORG, SECRETS_REPO_HOST to be set, I think they should not be a hard configuration requirement, instead, we should require for a key or keyring pair OR  secrets or and repo

**Comment by Rauno56** [comment]
Totally agree, but I'm not going yo add the change to this PR just yet. The org, repo host resolution is a bit flawed at this point anyways.

**Review by kanolato — APPROVED** [review]

**Comment by kanolato** [comment]
This is ready to be merged then :D

**Comment by Rauno56** [comment]
Did you test how much does it change the build times for you?

**Pull request merged**
